<?php

namespace Drupal\kino_content\Plugin\Field\FieldWidget;

use Drupal\Core\Field\FieldItemListInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Drupal\link\Plugin\Field\FieldWidget\LinkWidget;

/**
 * Plugin implementation of the 'link_imdb' widget.
 *
 * @FieldWidget(
 *   id = "link_imdb",
 *   label = @Translation("IMDB Link"),
 *   field_types = {
 *     "link"
 *   }
 * )
 */
class IMDBWidget extends LinkWidget {

  /**
   * {@inheritdoc}
   */
  public function formElement(FieldItemListInterface $items, $delta, array $element, array &$form, FormStateInterface $form_state) {
    $element = parent::formElement($items, $delta, $element, $form, $form_state); // TODO: Change the autogenerated stub
    $element['uri']['#description'] = $this->t('This must be a link to IMDB such as %url.', ['%url' => 'https://www.imdb.com/title/tt2948356']);
    return $element;
  }

  /**
   * {@inheritdoc}
   */
  public static function validateUriElement($element, FormStateInterface $form_state, $form) {
    parent::validateUriElement($element, $form_state, $form);
    $uri = static::getUserEnteredStringAsUri($element['#value']);

    if (parse_url($uri, PHP_URL_SCHEME) !== 'https' || !in_array(parse_url($uri, PHP_URL_HOST), ['www.imdb.com', 'imdb.com'])) {
      $form_state->setError($element, t('Must be an IMDB link.'));
      return;
    }
  }

  /**
   * {@inheritdoc}
   */
  public function massageFormValues(array $values, array $form, FormStateInterface $form_state) {
    $values = parent::massageFormValues($values, $form, $form_state);
    foreach ($values as &$value) {
      $value['uri'] = 'https://www.imdb.com' . parse_url($value['uri'], PHP_URL_PATH);
    }
    return $values;
  }

}
